### ISSUE TITLE
Splitting jackknife into separate module and interface proposal

### ISSUE THREAD

**Issue by HDembinski** [dsaxton/resample#22]
Since we are breaking things: I would prefer it if the jackknife tools lived in a resample.jackknife module. It seems more logical to import the jackknife from resample.jackknife and the bootstrap from resample.bootstrap. I hope this makes sense and is not controversal.

As a next step, I propose to have a common interface mirrored between the bootstrap and jackknife modules. With both jackknife and bootstrap, one can generate samples, compute bias, compute variance, compute a bias-corrected estimate.

Using the module as a namespace, one can create functions `sample`, `bias`, `variance`, `bias_corrected` in both modules and import functionality like this:
```
from resample import jackknife as jk
jk.bias(...)
jk.variance(...)
```
or
```
from resample.jackknife import variance as jvar
from resample.bootstrap import variance as bvar, bias as bbias
# use jvar, bvar, bbias
```

**Comment by dsaxton** [comment]
Sounds like a very good idea, that would be much cleaner. My only qualm would be that we not create a precedent for importing jackknife as jk since jk is short for "just kidding" 😄

**Comment by HDembinski** [comment]
Ok, should be careful about that in the docs :)
