### ISSUE TITLE
Contribution to PyHEP 2020?

### ISSUE THREAD

**Issue by HDembinski** [dsaxton/resample#26]
I took the liberty to submit an abstract to PyHEP 2020 virtual workshop on Python data analysis in high energy physics:

https://indico.cern.ch/event/882824/overview

I think this is a good place to advertise `resample` and what can be done with it. The workshop is very popular this year, so I went directly ahead in submitting the abstract without asking, but I can withdraw it if you don't think this is a good idea.

The presentation will mainly consist of a Jupyter notebook which show-cases the capabilities of `resample`, there will be some general information, too, like who is working on it, status, plans, etc.

**Comment by HDembinski** [comment]
I think the registration is CERN-members only, but if you are interested in giving the talk yourself, this can probably be arranged with the organisers. So far I registered myself as speaker.

**Comment by dsaxton** [comment]
I think that sounds like a great idea, and I am fine with you presenting if you'd like. We could also use this repository for the workshop notebook, and this could even be an opportunity to replace the current one which uses the now infamous Boston housing data set (I believe this has even been removed from the UCI Machine Learning Repository). Here is a discussion on this dataset: https://github.com/scikit-learn/scikit-learn/issues/16155

**Comment by HDembinski** [comment]
Wow, that thing with the B variable.

**Comment by dsaxton** [comment]
I'm going to go ahead and remove it, then we can work on replacing

**Comment by HDembinski** [comment]
The talk was well received, I think :). I have another talk today about iminuit, in which I will point to resample again.

**Comment by dsaxton** [comment]
> The talk was well received, I think :). I have another talk today about iminuit, in which I will point to resample again.

Feel free to add the notebook here

**Comment by HDembinski** [comment]
Link to notebook: https://github.com/HDembinski/pyhep-2020-resample/blob/master/resample.ipynb

**Comment by dsaxton** [comment]
> Link to notebook: https://github.com/HDembinski/pyhep-2020-resample/blob/master/resample.ipynb

I was also thinking to commit the actual notebook to the repo if you think that's appropriate

**Comment by HDembinski** [comment]
Yes, that would be great. Perhaps it can replace the other existing notebooks. Or perhaps we want to split it into smaller books on individual aspects?

**Comment by dsaxton** [comment]
> Yes, that would be great. Perhaps it can replace the other existing notebooks. Or perhaps we want to split it into smaller books on individual aspects?

I think simply replacing the two current notebooks is good. We'd just want to update with some of the recent changes like renaming functions (and be mindful that some of the other comments will also go out of date soon, e.g., that the code used is not released).
