### ISSUE TITLE
`mise` is implemented but not used, `sup_norm` is only used in a test

### ISSUE THREAD

**Issue by HDembinski** [dsaxton/resample#30]
Do we need to expose `mise`? It is not used anywhere (except in tests).

Similarly, `sup_norm` is used in one of the tests, but not by the main code. Is it necessary to expose this?

Generally, we should keep tools private (name starting with underscore) unless we want them to be used by users. The reason is that we can arbitrarily change private interfaces to our hearts content, but public interfaces always need to be deprecated, documented, etc.

So, if we need `mise` and `sup_norm` internally, I think they should start with an underscore.

**Comment by HDembinski** [comment]
Follow-up question: did you try `scipy.optimize.quad` on those? This is generally a great integration method, although I am not sure how well it performs on step-functions that are not differentiable.

**Comment by dsaxton** [comment]
@HDembinski I think they could be removed. I had used them a bit early on "for fun" to look at the convergence of certain functions like the ECDF and thought other people might also find them useful, but honestly they probably don't belong in the module.
