### ISSUE TITLE
new module `empirical`

### ISSUE THREAD

**Issue by HDembinski** [dsaxton/resample#31]
I think there are several tools which fit very nicely in a separate module called `empirical`.

`utils.ecdf` -> `empirical.cdf`
`utils.eqf` -> `empirical.quantile`
`jackknife.empirical_influence` -> `empirical.influence`

@dsaxton Sound good?

**Comment by HDembinski** [comment]
If that is ok with you, I would also include those changes in #28

**Comment by dsaxton** [comment]
That works for me. Then along with the removal of `mise` and `sup_norm` the entire utilities module could be replaced with a better-named one.

Only preference would be to rename `utils.eqf` -> `empirical.quantile_function` or something more explicit to emphasize that it's returning a _function_ rather than a single quantile. Perhaps something similar with `jackknife.empirical_influence` -> `empirical.influence_function` though I don't have as strong an opinion on that one.

**Comment by HDembinski** [comment]
How about `quantile_fn` and `influence_fn`?

**Comment by HDembinski** [comment]
I looked into scipy for inspiration, and it seems they use `X_gen` in this case, which seems fine to me, so I changed it to `quantile_gen` and `cdf_gen`.

**Comment by HDembinski** [comment]
To summarize our discussion from PR #28 , @dsaxton, you prefer the names

- quantile_function
- cdf

My favorites are
- quantile_gen
- cdf_gen

Here is a summary of my arguments:
- the `X_gen` suffix is also used by scipy (internally), see https://github.com/scipy/scipy/blob/2ea67057b1bbce3a253af89a92ee93ffc9c97525/scipy/stats/_discrete_distns.py#L18
- both quantile and cdf are higher-order functions, functions which return functions; this is unusual and so the fact should be indicated in their names
  - higher order functions are often used as factories, common choices for names of factories are `make_X`, `create_X`; I think these do not fit so well here
- names are the first level of documentation, good names remove the need to look up the documentation, because the code is obvious when you read it; that is always the goal
  - for that to work, names need to be chosen so that they appeal to the intuition of the programmer
  - anticipating what is intuitive is the core of good design and it depends on the expected user base

**Comment by HDembinski** [comment]
It will not break my heart if you insist on your choice, but I am also pretty confident in mine.

**Comment by dsaxton** [comment]
I can see it as potentially confusing that (for instance) quantile_function is not in fact a quantile function; I don't think it has anything to do with it a being higher-order function. I also think quantile_gen sounds very awkward and it's not obvious what it would mean from the name (it still isn't disambiguating between generating individual quantiles and quantile functions, for instance).

Maybe something like fit_quantile_function and fit_cdf would work better. It's pretty clear what they're doing from the names, and this matches the terminology statisticians / data scientists use when talking about these things.

**Comment by HDembinski** [comment]
> it still isn't disambiguating between generating individual quantiles and quantile functions, for instance

`quantile_gen` makes a function that a user can call `quantile` in their code or `q` or `quant`, which computes quantiles. I think that is natural.

**Comment by HDembinski** [comment]
I think `fit_X` is not a good name, because we are not (maximum-likelihood) fitting anything.

When you say that `quantile_gen` sounds awkward, please consider that scipy chose exactly this name. If it passes scipy's reviewing process, then it cannot be a bad name.

**Comment by dsaxton** [comment]
> I think `fit_X` is not a good name, because we are not (maximum-likelihood) fitting anything.

We're fitting functions to data, and actually we are using maximum likelihood: https://stats.stackexchange.com/a/110694. However I don't think this matters, the term "fit" is used all the time to mean more than just estimating parameters via maximum likelihood (see the numerous fit methods within scikit-learn).

**Comment by HDembinski** [comment]
In my field, "a fit" is 99% something where you do a numerical optimisation of a cost function, mostly the likelihood function. This is not what we are doing here. 

A "fit" implies that this is a costly operation. The quantile and cdf functions do a little bit of work, but not nearly as much as a numerical optimisation. Generating the CDF is a computation and not a fit, even though the empricial cdf is a maximum-likelihood estimate. You wouldn't call computing the arithmetic mean of a normal distribution a fit, even though the arithmetic mean is the maximum likelihood estimator of the normal distribution.
