### ISSUE TITLE
Remove numba?

### ISSUE THREAD

**Issue by HDembinski** [dsaxton/resample#33]
Thanks to #28 I am now also familiar with the bootstrap implementations. I couldn't find an obvious way to accelerate the code with numba, and in the meantime I also found a pure-numpy implementation of the jackknife resampling, which is as fast as the numba implementation, meaning that the numba implementation is now obsolete.

Therefore, I think we can drop numba. If we want to merge this into scipy, it is going be easier without the numba dependency, because scipy does not require numba.

**Comment by dsaxton** [comment]
What was the numpy implementation for the jackknife?

**Comment by HDembinski** [comment]
```py
# pure numpy implementation of jackknife resampling
def resample(fn, sample):
    n = len(sample)
    x = sample[1:].copy()
    # yield x0
    yield x

    # update of x needs to change values only up to i
    # for a = [0, 1, 2, 3]
    # x0 = [1, 2, 3] (yielded above)
    # x1 = [0, 2, 3]
    # x2 = [0, 1, 3]
    # x3 = [0, 1, 2]
    for i in range(n - 1):
        x[i] = sample[i]
        yield x
```

**Comment by HDembinski** [comment]
I benchmarked this, it is as fast as the numba version (which was doing unnecessary work, but even if that is fixed, this version is as fast).

**Comment by dsaxton** [comment]
Probably a good idea to remove if we can get the same speed without

**Comment by dsaxton** [comment]
Can you submit a PR for this after the interface one is merged?

**Comment by HDembinski** [comment]
Yes

**Comment by HDembinski** [comment]
See #38
