### ISSUE TITLE
When to fix scale and location of parametric family?

### ISSUE THREAD

**Issue by HDembinski** [dsaxton/resample#35]
In the current parametric bootstrap, location and scale parameters are fixed for some families. I think this definitely makes sense for some distributions, for example, we don't want to change the location of the Poisson, beta, gamma, or exponential distribution. But there are some distributions which can be used as approximations to real-life distributions.

For example, the student's t distribution is a useful for data that is approximately normally distributed, but has heavier tails, but that would require that the scale parameter of the student's t distribution is fitted to the data set.

We should discuss here whether generalizing some parametric families makes sense and which are candidates for such a generalization.

**Comment by dsaxton** [comment]
> For example, the student's t distribution is a useful for data that is approximately normally distributed, but has heavier tails, but that would require that the scale parameter of the student's t distribution is fitted to the data set.

Regarding this case specifically we _are_ estimating the degrees of freedom, which is a scale parameter that controls the heaviness of tails. I'm actually not sure why scipy has two scale parameters for this distribution.

**Comment by HDembinski** [comment]
In the t-distribution, the nu parameter changes the variance a little bit, but not much. 
https://en.wikipedia.org/wiki/Student's_t-distribution
The variance is nu / (nu - 2) for nu > 2. If the data you want to approximate with a t distribution happens to have a larger variance than that, the fit will not work. The nu parameter mostly changes the tails of the distribution, while the scale parameter changes the overall width.

**Comment by dsaxton** [comment]
> In the t-distribution, the nu parameter changes the variance a little bit, but not much.
> https://en.wikipedia.org/wiki/Student's_t-distribution
> The variance is nu / (nu - 2) for nu > 2, which goes to 1 for nu -> infty. If the data you want to approximate with a t distribution happens to have a larger variance than that, the fit will not work. The nu parameter mostly changes the tails of the distribution, while the scale parameter changes the overall width.

The variance there _decreases_ to one as nu increases and goes to infinity for small values. Now that I think about it more they probably added the extra parameter so the variance can be less than one, which makes sense.

**Comment by HDembinski** [comment]
In my application, I am using the t-distribution to fit peaks of particle resonances. Fundamentally, these have a Cauchy distribution, but due to non-trivial randomness added by the detector, you get something more alike to a normal distribution, but not quite. The t distribution interpolates between a cauchy and a gaussian distribution and is therefore suited for an emprical fit. My particle resonances have variances that are completely different from that of the t-distribution. To apply the parametric bootstrap on that, fscale needs to be free.
