### ISSUE TITLE
readthedocs build is broken

### ISSUE THREAD

**Issue by HDembinski** [dsaxton/resample#37]
See https://readthedocs.org/projects/resample/builds/

I can probably fix this if you give me admin rights on readthedocs.

**Comment by HDembinski** [comment]
From looking at the logs, it fails because it is building the docs on Python2.

**Comment by dsaxton** [comment]
@HDembinski If we can get the documentation working then it may be a good time to release the 1.0.0 version, as I don't think there are any other breaking changes we're planning to make. What do you think?

**Comment by HDembinski** [comment]
We need to resolve #34 before 1.0

**Comment by HDembinski** [comment]
Sorry that there was no progress on this, but the last week was pretty intense for me with 2.5 presentations and many features added a day before the presentation.

**Comment by HDembinski** [comment]
fixed
