### ISSUE TITLE
Confidence interval of correlation coefficient

### ISSUE THREAD

**Issue by MatthiVH** [dsaxton/resample#4]
Hi there,

I have to say that your bootstrapping-library is one of the cleanest I have seen so far, with lots of easy to use options. There's not that much around for bootstrapping, correlation and confidence intervals in Python.

I however had a question: When calculating confidence intervals of a correlation coefficient, I found in the example here(https://github.com/dsaxton/resample/blob/master/examples/resample.ipynb), I was wondering if you could also use the other ci-options as 'bca' or 't' or can you only use the 'percentile'-ci-option when calculating confidence intervals of a correlation coefficient between two variables. I came across an error, that's why I had this question. For single dataframes, the options seem to work, but for correlated dataframes, they give an error.

And secondly: the 'f'-parameter in bootstrap.bootstrap_ci(), what type of data does it need, for example in a correlation analysis. Can you only set something like 'lambda x: np.corrcoef(x[:, 0], x[:, 1])[0, 1]' such as in the example? or can you also just type the correlation coefficient or some function with the 'permutation.corr_test'-function you have. I'm just wondering what the 'f'-parameter needs as input there, what is it used for, what does it do.

Kind regards

**Comment by dsaxton** [comment]
Hi @MatthiVH, thanks for the feedback! Can you show what error you're seeing? You should be able to use any of the three confidence interval methods for correlation coefficients. Here I'm running it on some random 100 x 2 Gaussian data:
```python
[ins] In [16]: bootstrap.bootstrap_ci(x, f=lambda a: np.corrcoef(a.T)[0, 1], ci_method="percentile")
Out[16]: (-0.08828465520333718, 0.028270722656782835)

[ins] In [17]: bootstrap.bootstrap_ci(x, f=lambda a: np.corrcoef(a.T)[0, 1], ci_method="bca")
Out[17]: (-0.08304231505995482, 0.02373977659682548)

[ins] In [18]: bootstrap.bootstrap_ci(x, f=lambda a: np.corrcoef(a.T)[0, 1], ci_method="t")
Out[18]: (-0.07217097371373642, 0.02590076256752869)
```
The f parameter in the bootstrap functions can be thought as any callable that takes the original data as input and returns a scalar value as output (essentially an arbitrary statistic). Here I'm making up a function that returns the proportion of times the first column is less than the second and getting a confidence interval on the associated parameter:
```python
[ins] In [20]: bootstrap.bootstrap_ci(x, f=lambda a: (a[:, 0] < a[:, 1]).mean(), ci_method="t")
Out[20]: (0.49, 0.543)
```
Hope this helps.
