### ISSUE TITLE
Replace empirical.cdf_fn by textbook implementation

### ISSUE THREAD

**Issue by HDembinski** [dsaxton/resample#44]
The current implementation is applying linear interpolation, but that is not how the empirical CDF looks like in text books, which does steps. Changing the implementation to the official form will also resolve the TODO.

**Comment by HDembinski** [comment]
Sorry, nevermind, the CDF is correct, I was thinking about the quantile function. I am not sure whether we should to interpolation there...

**Comment by dsaxton** [comment]
> Sorry, nevermind, the CDF is correct, I was thinking about the quantile function. I am not sure whether we should to interpolation there...

I think we probably should not, since we should think of it as the quantile function of a discrete distribution with point masses at the observed data points
