### ISSUE TITLE
Remove method "student" in bootstrap.confidence_interval

### ISSUE THREAD

**Issue by HDembinski** [dsaxton/resample#49]
The method "student" is not implementing the bootstrap-t method as described in the book by Efron and Tibshirani, page 160+.

In the book, the algorithm estimates the standard deviation for each bootstrap replica, which requires a double bootstrap. Let's say the estimator is s(x)
- replicate a sample x* from the original sample x and compute s(x*)
- bootstrap the std. deviation of s(x*) by bootstrapping again from x*, generating several replicas s(x**)
- compute the studentized values (s(x*) - s(x))/std of s(x**)
- generate a quantile function of these values and compute the interval from that

This differs from the implemention we have, which computes the std.dev. of s(x*), not std.dev. of s(x**). The difference is important. Our current implementation is identical to the percentile, because the percentile is transformation independent and we just apply a scaling and a shift to the bootstrap replicas.

Our options are to implement the bootstrap-t properly or to remove this method. I am in favor of removing, because the bootstrap-t is shown to be inferior to the bca method in the book, while being computationally even more expensive.

**Comment by dsaxton** [comment]
Another option would be to use the jackknife to estimate the standard deviation within each bootstrap sample as a less expensive alternative, but from what I'm seeing that's still pretty slow. So probably best to remove for now.

**Comment by HDembinski** [comment]
Comment: the jackknife is only faster for small samples.
