### ISSUE TITLE
Default value for number of bootstrap replicas?

### ISSUE THREAD

**Issue by HDembinski** [dsaxton/resample#51]
The default value for the number of bootstrap replicas used to be 100. I changed this at some point to 1000, but I thought I had changed it back, but I see that the current master has the value 1000.

A value of 100 should be good enough for a first estimate, I think we should switch back to 100. @dsaxton What do you think?

**Comment by HDembinski** [comment]
From brushing up on Efron's book and from doing numerical tests, I think the original default value of 100 was appropriate.

**Comment by dsaxton** [comment]
I had also thought of potentially having no default, with the idea being that the user should perhaps _always_ have to think consciously about how many bootstrap replicates they'll be working with. Thoughts?

Otherwise, I think erring on the side of a less computationally intensive default makes sense.

**Comment by HDembinski** [comment]
There are definitely arguments for not offering a default at all to enforce a decision, I also considered this when I read your original code. But then I concluded that I like your decision to offer the default. For people who are just starting with the library, who cannot make an educated choice, it is good to have a reasonable default that will work most likely. Having a default value also maintains the symmetry between jackknife and bootstrap:

```
from resample.bootstrap import resample # just replace bootstrap with jackknife to switch

for resampled in resample(original_sample):
   # do stuff
```

**Comment by HDembinski** [comment]
For the future, I got some ideas from Efron's book on how to pick the number of bootstrap samples automatically. The variance of a bootstrap estimate has the following form var = 1 / n (c_1 / n + c_2 / B) [also see my PyHEP presentation], where n is the number of observations in the original sample and B is the number of bootstrap replicas.

An automatic choice for B is to stop when the second term becomes sub-dominant, e.g. c_2 / B == 0.5 c_1 / n. We don't know the constants c_1 and c_2 beforehand, but they can be estimated live by monitoring the variance of the output of the function applied to the bootstrapped sample as a function of the number of replicas.

**Comment by dsaxton** [comment]
I'm seeing that the default is still 100 so I think this can be closed since that seems to be what we want?

https://github.com/dsaxton/resample/blob/7d6a3bdedaba9df805ac313148281c9fdff2fe74/resample/bootstrap.py#L104

**Comment by HDembinski** [comment]
Ah I see now, I fixed it in bootstrap.bootstrap, but forgot to change the default also in bootstrap.resample.
