### ISSUE TITLE
Default value for ci_method in confidence_interval?

### ISSUE THREAD

**Issue by HDembinski** [dsaxton/resample#52]
I think the default value for ci_method in confidence_interval should be bca. I haven't numerically tested this myself, but according to Efron's book, the bca method should give more accurate confidence intervals for the same number of bootstrapped samples.

**Comment by dsaxton** [comment]
I think so too, we should use default values to encourage best practices

**Comment by dsaxton** [comment]
Fixed by https://github.com/dsaxton/resample/pull/53
